### ISSUE TITLE
Context browser's panel chevron misaligned in certain viewport sizes.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-context-browser#63]
Context Browser's chevron gets misaligned with the icon in IE11 only when dev tool is open.
The chevron remains aligned in all other browsers with or without the dev tools open.

## Environment :
CB: Redesign Branch/today's pull
app-helpers: Master/today's pull

Browser: IE11 on win7 (when dev tools are open)
Browser: Safari on ios(iphone plus)

### IE11 dev tools open
![2017-07-14_1223](https://user-images.githubusercontent.com/10835611/28228219-5dc83fde-6892-11e7-8adb-1e937dc99272.png)

### IE11 devtools closed

![2017-07-14_1251](https://user-images.githubusercontent.com/10835611/28228429-5e03a7c6-6893-11e7-841d-e878e58a2456.png)

### iphone:

![img_0018](https://user-images.githubusercontent.com/10835611/28587951-ab77c4f4-712d-11e7-98a3-7414796e4d55.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
This is a tough one, I think we'll need to talk through with the designers. This is happening because the context browser dropdown is trying to stay as large as possible when the window shrinks (e.g. not scroll off bottom items when there is additional space above the button). I'm not sure how we should handle this tradeoff ... the pointer is pointed at the wrong location, but the user can see more of the items in the context browser.
